//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OQC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeNG
    {
        public int ID { get; set; }
        public string TypeNG1 { get; set; }
        public string JP { get; set; }
    }
}
